# Generated by Django 5.0.6 on 2024-09-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=49)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "ifsc",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("branch", models.CharField(max_length=74)),
                ("address", models.CharField(max_length=195)),
                ("contact", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=26)),
                (
                    "bank_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.bank"
                    ),
                ),
            ],
        ),
    ]
